version: '3.8'

services:
  app:
    build:
      context: ./GO
    ports:
      - "8081:8081"
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      BASE_DSN: root:1234@tcp(db:3306)/
      TARGET_DB: company
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      SERVER_ADDRESS: :8081
      CONTEXT_TIMEOUT: 2
      ACCESS_TOKEN_EXPIRY_HOUR: 2
      REFRESH_TOKEN_EXPIRY_HOUR: 168
      ACCESS_TOKEN_SECRET: access_token_secret
      REFRESH_TOKEN_SECRET: refresh_token_secret

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "company"
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  consumer:
    build:
      context: ./RabbitConsumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/

volumes:
  dbdata:
